# [Info]
# 左上角标题
site_name: Wu-wu-u's Notebooks
site_url: https://github.com/Wu-wu-u/Notebooks
site_author: Wu-wu-u
repo_url: https://github.com/Wu-wu-u/Notebooks
repo_name: Wu-wu-u/Notebooks
copyright: Copyright &copy; 2023-2024 <a herf="https://github.com/Wu-wu-u" target="_blank" rel="noopener">Wu-wu-u</a>

theme:
  name: material
  language: zh # 语言设置为中文(会改变搜索栏/最后修改 等文字)，默认为英文
  #logo: assets/logo.jpg # 页面中顶部栏左侧图标
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github # git-alt/github-alt
    annotation: material/arrow-right-circle
    logo: material/notebook-outline
  font: False
  palette:
    # 日间模式
    - media: "(prefers-color-scheme: light)"
      scheme: default

      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: white

      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      # accent: teal
        
    #   toggle:
    #     # 图标
    #     icon: material/weather-sunny
    #     # 鼠标悬浮提示
    #     name: 切换至夜间模式
    # # 夜间模式
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: black
    #   accent: blue
    #   toggle:
    #     icon: material/weather-night
    #     name: 切换至日间模式
  features:
    - toc.follow # 右侧目录随页面滑动

    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs

    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top

    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes

    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    # - navigation.expand

    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy

    # 可以在代码块中内嵌注释
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations
    - content.code.annotate

    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest

    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Wu-wu-u

extra_css:
  - css/custom.css  
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.18/dist/katex.min.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 5
  - admonition #应用admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite #添加了对内联代码块的语法突出显示的支持
  - pymdownx.snippets #使用简单语法将任意文件的内容嵌入到文档
  - pymdownx.superfences: #允许代码和内容块任意嵌套，包括警告、选项卡、列表和所有其他元素
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details #admonition可以折叠

  - attr_list #允许使用特殊语法将 HTML 属性和 CSS 类添加到几乎每个Markdown 内联和块级元素。
  - md_in_html
  - pymdownx.keys #添加了一个简单的语法来允许呈现键盘按键和组合 

  # Caret 、 Mark和Tilde扩展添加了使用简单语法突出显示文本并定义下标和上标的功能。
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.critic #允许使用Critic 标记来突出显示文档中添加、删除或更新的部分，即跟踪 Markdown 语法的更改。

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  # 相关内容或者代码块可以分组展示
  - pymdownx.tabbed:
      alternate_style: true
  
  # 允许使用任务清单即- []      
  - pymdownx.tasklist:
      custom_checkbox: true
  
  # 允许渲染公式，还需要添加mathjax配置和JavaScript      
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#arithmatex
  - pymdownx.arithmatex:
      generic: true

  - def_list #使用各类表格
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  - sane_lists
  - pymdownx.magiclink


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js 

plugins:
  - glightbox #图片放大
  
  - statistics: #统计页面字数、代 码行数、阅读时间
    #https://github.com/TonyCrane/mkdocs-statistics-plugin  
  - search
  - git-revision-date-localized


nav:
  - Home:
    - index.md
  - Computer Science:
    - cs/index.md
    - 编程语言:
        - C/C++:
          - C语言: cs/pl/c_cpp/C/c.md
          - C++: cs/pl/c_cpp/CPP/cpp.md
        - python:
          - 基础语法: cs/pl/python/Syntax/syntax.md
          - CS61A: 
            - cs/pl/python/CS61A/index.md
            - 函数与列表: cs/pl/python/CS61A/cs61a.md
            - 面向对象编程: cs/pl/python/CS61A/object.md
        - x86 汇编语言: cs/pl/asm/asm.md
    - 计算机系统:
        - Verilog: cs/systems/Verilog/verilog.md
        - 数字逻辑设计: 
          - cs/systems/LCDF/index.md
          - Chapter1  Digital Systems and Information: cs/systems/LCDF/Chapter1.md
          - Chapter2  Combinational Logic Circuits: cs/systems/LCDF/Chapter2.md
          - Chapter3  Combinational Logic Design: cs/systems/LCDF/Chapter3.md
          - Chapter4  Sequential Circuits: cs/systems/LCDF/Chapter4.md
          - Chapter5  Digital Hardware Implementation: cs/systems/LCDF/Chapter5.md
          - Chapter6  Registers & Register Transfers: cs/systems/LCDF/Chapter6.md
          - Chapter7  Memory Basics: cs/systems/LCDF/Chapter7.md
        - 计算机组成: 
          - cs/systems/CO/index.md
          - 1.Preface: cs/systems/CO/preface.md
          - 2.Instructions: cs/systems/CO/instruction.md
          - 3.Arithmetic: cs/systems/CO/arithmetic.md
          - 4.Processor: cs/systems/CO/processor.md
          - 5.Cache: cs/systems/CO/cache.md
          - 6.I/O: cs/systems/CO/IO.md
    - 算法相关:
      - 数据结构基础: 
        - cs/algorithm/FDS/index.md
        - Chapter 2 Algorithm Analysis: cs/algorithm/FDS/chapter2.md
        - Chapter 3 Lists,Stacks,and Queues: cs/algorithm/FDS/chapter3.md
        - Chapter 4 Trees: cs/algorithm/FDS/chapter4.md
        - Chapter 5 Priority Queues: cs/algorithm/FDS/chapter5.md
        - Chapter 6 Sorting: cs/algorithm/FDS/chapter6.md
        - Chapter 7 Hashing: cs/algorithm/FDS/chapter7.md
        - Chapter 8 The Disjoint Set: cs/algorithm/FDS/chapter8.md
        - Chapter 9 Graph Algorithms: cs/algorithm/FDS/chapter9.md
        - 题目集: cs/algorithm/FDS/problems.md
      - 高级数据结构:
        - cs/algorithm/ADS/index.md
        - Amortized analysis: cs/algorithm/ADS/amortized.md
        - lec1|Avl Trees & Splay Trees: cs/algorithm/ADS/lec1.md
        - lec2|Red Black Trees & B+ Trees: cs/algorithm/ADS/lec2.md 
        - lec3|Inverted File Index: cs/algorithm/ADS/lec3.md
        - lec4|Leftise Heaps & Skew Heaps: cs/algorithm/ADS/lec4.md
        - lec5|Binomial Queue: cs/algorithm/ADS/lec5.md
        - lec6|Search & Backtracing: cs/algorithm/ADS/lec6.md
        - lec7|Divide & Conquer: cs/algorithm/ADS/lec7.md
        - lec8|Dynamic Programming: cs/algorithm/ADS/lec8.md
        - lec9|Greedy Algorithm: cs/algorithm/ADS/lec9.md
        - lec10|NP completeness: cs/algorithm/ADS/lec10.md
        - lec11|Approximation: cs/algorithm/ADS/lec11.md
        - lec12|Local Search: cs/algorithm/ADS/lec12.md
        - lec13|Randomized Algorithm: cs/algorithm/ADS/lec13.md
        - lec14|Parallel: cs/algorithm/ADS/lec14.md
        - lec15|External Sort: cs/algorithm/ADS/lec15.md
    - 理论相关:
      - 离散数学: 
        - Chapter 1 Logic and Proofs: cs/theories/Discrete_Math/chapter1.md
        - Chapter 2 Basic Structures: cs/theories/Discrete_Math/chapter2.md
        - Chapter 3 Algorithm: cs/theories/Discrete_Math/chapter3.md
        - Chapter 4 Number Theory and Cryptography: cs/theories/Discrete_Math/chapter4.md
        - Chapter 5 Induction and Recursion: cs/theories/Discrete_Math/chapter5.md
        - Chapter 6 Counting: cs/theories/Discrete_Math/chapter6.md
        - Chapter 8 Advanced Counting Techniques: cs/theories/Discrete_Math/chapter8.md
        - Chapter 9 Relations: cs/theories/Discrete_Math/chapter9.md
        - Chapter 10 Graphs: cs/theories/Discrete_Math/chapter10.md
        - Chapter 11 Trees: cs/theories/Discrete_Math/chapter11.md
    - 人工智能:
      - 基础库的使用: cs/AI/basic_module.md  
    - 工具相关:
      - Git: cs/tools/git/git.md
      - Latex: cs/tools/latex/latex.md
      - Vim: cs/tools/vim/vim.md
      - GDB: cs/tools/gdb/gdb.md
      - Make: cs/tools/make/make.md
      - Docker: cs/tools/docker/docker.md
      - Mkdocs: 
        - Build Website: cs/tools/mkdocs/Build_Website.md
        - 配置: cs/tools/mkdocs/mkdocs.md
  - Others:
    - others/index.md
    - 课程记录:
      - CTF101: 
        - others/lessons/CTF/index.md
        - Web: others/lessons/CTF/web.md
        - Crypto: others/lessons/CTF/crypto.md
        - Reverse: others/lessons/CTF/reverse.md
        - Pwn: others/lessons/CTF/pwn.md
        - Misc: others/lessons/CTF/misc.md
      - 微信小程序开发:
        - others/lessons/WX/index.md
        - HTML基础: others/lessons/WX/basic.md
        - CSS基础: others/lessons/WX/css.md
        - JavaScript基础: others/lessons/WX/js.md
        - JS RegExp: others/lessons/WX/reg.md
        - Tips: others/lessons/WX/tips.md  
        - 微信开发者工具: others/lessons/WX/dev.md
      - 无线网络应用:
        - others/lessons/WLAN/index.md
        - 课程知识: others/lessons/WLAN/wlan.md

